plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
defaults:
  - scope:
      path: ""   # applies to all files
      type: "pages"
    values:
      layout: default